name: Deploy to Firebase

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Build Next.js app
      run: yarn build:substrate

    - name: Deploy to Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      run: |
        echo "${FIREBASE_SERVICE_ACCOUNT}" > firebase-service-account.json
        yarn global add firebase-tools
        firebase login:ci --token "${FIREBASE_TOKEN}" # Log in to Firebase using the token
        firebase deploy --project $FIREBASE_PROJECT_ID --token "${FIREBASE_TOKEN}" --non-interactive
        rm firebase-service-account.json
